### PR TITLE
Update underscore script to 1.13.2

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

### CODE REVIEW

**Comment by ALazyMeme** [comment]
I have no idea how to effectively test this, since underscore.js doesn't seem to have just 1 feature to it. If anyone has any suggestions, I'd be happy to hear.

**Comment by RAnders00** [comment]
You could take a look at the changelog for underscorejs and look at the breaking changes for v1->v2 and v2->v3

**Comment by ALazyMeme** [comment]
Lots of fixes and additions, I don't see any breaking changes: https://underscorejs.org/#changelog

**Review by pajlada — APPROVED** [review]
We only use the [_.escape](https://underscorejs.org/#escape) function which doesn't seem to have had any changes.

**Pull request merged**
