### PR TITLE
Library update

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

I'll test this

### CODE REVIEW

**Comment by ALazyMeme** [comment]
Yes this works

**Comment by pajlada** [comment]
emote combo doesn't work

**Comment by pajlada** [comment]
chart library doesn't load anymore

**Comment by pajlada** [comment]
moment doesn't load:
None of the “sha256” hashes in the integrity attribute match the content of the subresource. 2 modules

**Comment by ALazyMeme** [comment]
It might be best if I update these per pr

**Pull request closed without merging**
