### PR TITLE
Subemotes PR fix

### LINKED ISSUE #752: New subemotes pr breaks the bot
@pajlada https://github.com/pajbot/pajbot/pull/716
```Jan 15 09:46:15 FeelsOkayBot systemd[1]: Started pajbot for alazymeme.
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,669] [DEBUG  ] Loaded config
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,690] [INFO   ] PostgreSQL Server notice: NOTICE:  relation "schema_version" already exists, skipping
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,691] [DEBUG  ] migrate db: current revision ID is 11
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,691] [DEBUG  ] migrate db: 0 revisions to run
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,693] [DEBUG  ] migrate redis: current revision ID is 1
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,693] [DEBUG  ] migrate redis: 0 revisions to run
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,912] [INFO   ] Loaded 5 timers (4 online/1 offline)
Jan 15 09:46:16 FeelsOkayBot python3[29311]: [2020-01-15 09:46:16,912] [ERROR  ] Logging an uncaught exception
Jan 15 09:46:16 FeelsOkayBot python3[29311]: Traceback (most recent call last):
Jan 15 09:46:16 FeelsOkayBot python3[29311]:   File "main.py", line 74, in <module>
Jan 15 09:46:16 FeelsOkayBot python3[29311]:     run(args)
Jan 15 09:46:16 FeelsOkayBot python3[29311]:   File "main.py", line 40, in run
Jan 15 09:46:16 FeelsOkayBot python3[29311]:     pajbot = Bot(config, args)
Jan 15 09:46:16 FeelsOkayBot python3[29311]:   File "/opt/pajbot/pajbot/bot.py", line 198, in __init__
Jan 15 09:46:16 FeelsOkayBot python3[29311]:     self.emote_manager = EmoteManager(self.twitch_v5_api, self.twitch_legacy_api, self.action_queue)
Jan 15 09:46:16 FeelsOkayBot python3[29311]:   File "/opt/pajbot/pajbot/managers/emote.py", line 141, in __init__
Jan 15 09:46:16 FeelsOkayBot python3[29311]:     self.twitch_emote_manager = TwitchEmoteManager(twitch_v5_api, twitch_legacy_api)
Jan 15 09:46:16 FeelsOkayBot python3[29311]: TypeError: __init__() takes 1 positional argument but 3 were given
Jan 15 09:46:17 FeelsOkayBot systemd[1]: pajbot@alazymeme.service: Main process exited, code=exited, status=1/FAILURE
Jan 15 09:46:17 FeelsOkayBot systemd[1]: pajbot@alazymeme.service: Failed with result 'exit-code'.

### PR DESCRIPTION
**Pull request by RAnders00**
#752 
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
@alazymeme Would you mind trying this?

**Comment by pajlada** [comment]
I'll review this tonight

**Comment by pajlada** [comment]
@alazymeme yeah please try this out when you can - I think the changes we have made should have made this functional

**Comment by alazymeme** [comment]
Bot boots and the subemotes command works now:
image

**Pull request merged**
