### PR TITLE
Update chart script to 3.7.1

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

### CODE REVIEW

**Comment by ALazyMeme** [comment]
I made the change entry intentionally broad - these changes shouldn't really affect users, so I plan on grouping multiple prs into the 1 changelog entry.

**Review by ajinkyagitrepo — APPROVED** [review]
why do i have access to this

**Comment by pajlada** [comment]
Have you tested this in the sense of actually having a chart show up? or just "doesn't crash xd"

**Comment by ALazyMeme** [comment]
> Have you tested this in the sense of actually having a chart show up? or just "doesn't crash xd"

I tested the CLR page to make sure it worked (since that's where it seems to be used). I'm not actually quite sure where the chart is though 🤔

**Comment by RAnders00** [comment]
I believe it‘s used when a prediction (via the prediction module) is ongoing. It shows a pie chart iirc

**Comment by ALazyMeme** [comment]
> I believe it‘s used when a prediction (via the prediction module) is ongoing. It shows a pie chart iirc

Looks like it might actually be the hsbet module, might see to removing it as well.

**Comment by pajlada** [comment]
Closing in favour of #1864

**Pull request closed without merging**
