### PR TITLE
Full prediction module removal

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

### CODE REVIEW

**Review by RAnders00 — CHANGES_REQUESTED** [review]
Can't you remove https://github.com/pajbot/pajbot/blob/3610d47181be2b3d376c286e8b91bc52d75574f3/templates/clr/overlay.html#L22 now?

**Comment by ALazyMeme** [comment]
> Can't you remove
> 
> https://github.com/pajbot/pajbot/blob/3610d47181be2b3d376c286e8b91bc52d75574f3/templates/clr/overlay.html#L22
> 
> now?

This leads me to believe that it's actually the hsbet module that uses charts, not the prediction module.
https://github.com/pajbot/pajbot/blob/3610d47181be2b3d376c286e8b91bc52d75574f3/templates/clr/overlay.html#L25=

**Comment by RAnders00** [comment]
Ah yeah, all right. That‘d make more sense as a separate PR then.

**Review by RAnders00 — APPROVED** [review]

**Comment by ALazyMeme** [comment]
Did some testing, this seems to work as intended.

**Pull request merged**
