### PR TITLE
Condense if statement in subscriber exemption in link checker module

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
What‘s the point of this change? We still use „is True“ in a lot of other places too

**Comment by alazymeme** [comment]
> What‘s the point of this change? We still use „is True“ in a lot of other places too

To remove some useless code? That's pretty much it

**Comment by RAnders00** [comment]
I mean like, just in the little preview github gives me around your change i can see three more pointless "is True" statements, i just don't get why that one in particular is so outstanding and why you didnt change the other ones too.

**Comment by alazymeme** [comment]
> I mean like, just in the little preview github gives me around your change i can see three more pointless "is True" statements, i just don't get why that one in particular is so outstanding and why you didnt change the other ones too.

I didn't notice the other ones. Will fix them up when I get the chance.

**Comment by pajlada** [comment]
This feels like a change that will only risk messing some things up if done in mass, and have no purpose if done in one place.
Not really a change fit for a project that's "frozenish"

**Pull request closed without merging**
