### PR TITLE
Migrate Game/Title fetching from Kraken v5 to Helix

### LINKED ISSUE #998: Move game + title fetching to helix
The current implementation isn't the best. When I use a game/title variable, I want to fetch the game/title at that current time. We shouldn't be requiring 2 separate variables.

### PR DESCRIPTION
**Pull request by pajlada**
This PR outgrew itself a bit, instead of only doing Game/Title fetching in Helix instead of Kraken v5, we also fetch video/stream information from Helix, and we use Helix for setting Game/Title.

During development, I started using mypy for getting early warnings in case I was sending the wrong parameters in somewhere, and it spreads very easily so there's a commit that adds typing to a few things that aren't related to this migration. If needed, this can be made into its own PR (including the addition of mypy to `requirements-dev.txt`)

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

Fixes #998

### CODE REVIEW

**Comment by alazymeme** [comment]
Any news on this PR? peepoZoom

**Comment by alazymeme** [comment]
@RAnders00 can you review pls alazymeme

**Review by RAnders00 — APPROVED** [review]

**Comment by pajlada** [comment]
Will merge next weekend while letting it run on my bots - will also think about the office() comment

**Review by RAnders00 — CHANGES_REQUESTED** [review]
This will need to be updated, right? https://github.com/pajbot/pajbot/blob/ce23381abd10fb3208d3c1b0a9c4b6b1bc45b163/templates/home.html#L8 Since the "online" key was removed.

**Comment by pajlada** [comment]
> This will need to be updated, right?
> 
> https://github.com/pajbot/pajbot/blob/ce23381abd10fb3208d3c1b0a9c4b6b1bc45b163/templates/home.html#L8
> Since the "online" key was removed.

No I don't think so, the removed online key from the `UserStream` class is unused as far as I can tell. This `stream_data` object is fetched from Redis from here https://github.com/pajbot/pajbot/blob/fix/migrate-game-title-fetching-from-kraken-to-helix/pajbot/web/routes/base/home.py#L20-L23 and populated from https://github.com/pajbot/pajbot/blob/fix/migrate-game-title-fetching-from-kraken-to-helix/pajbot/models/stream.py#L283

**Comment by pajlada** [comment]
After testing, the only thing I noticed was that the bot needs a restart when the Streamer has reauthenticated through the `/streamer_login` route to provide the required scope for `!settitle` and `!setgame` (or you could run `!eval bot.streamer_access_token_manager.initialize()` (maybe `.refresh()` is enough). I don't feel like that fits within the scope of this PR though

**Comment by alazymeme** [comment]
Merge soon? PauseChamp

**Review by RAnders00 — APPROVED** [review]
👍 Merge it when you think it's been tested for long enough FarmingCommits

**Comment by alazymeme** [comment]
PauseChamp

**Pull request merged**
