### PR TITLE
updated install-docs/readme.md further-steps

### PR DESCRIPTION
**Pull request by Felanbird**
~~**don't approve until #688 is completed**~~

added new commands + aliases
~~removed --reply~~
~~changed $(source:name) to $(source:username_raw)~~
~~added $(tb:broadcaster)~~
added $(tb:bot_domain)

Pull request checklist:
- [X] `CHANGELOG.md` was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
- `$(source:name)` is equivalent to `$(source:username_raw)` - they are both the display name.
- Why remove `--reply`? Reply means if the command is whispered e.g. by mods/the bot owner the response will be a whisper as well instead of a "say" to chat.

Apart from that, the other points are good improvements that I'll happily accept! 🚀

**Comment by Felanbird** [comment]
> * `$(source:name)` is equivalent to `$(source:username_raw)` - they are both the display name.
> * Why remove `--reply`? Reply means if the command is whispered e.g. by mods/the bot owner the response will be a whisper as well instead of a "say" to chat.
> 

I was mistaken on the part of --reply which is why I did already re-include it. ebfe1a5

As for $(source:name) vs $(source:username_raw) I was under the impression that $(source:username_raw) took capitalization into consideration and $(source:name) did not, which I have realized is not true so I will revert. 👍 
image

**Comment by Felanbird** [comment]
despite what github thinks the [changelog is correct](https://github.com/Felanbird/pajbot/blob/installdocs-readme-changes/CHANGELOG.md)
probably the 🤠 way I did it though

**Comment by RAnders00** [comment]
username_raw has become name, and username has become login, because that‘s what twitch calls it these days. https://github.com/pajbot/pajbot/blob/1c500fd88bbbd9c3f22986ba1df16a0af9af294c/docs/variables.txt#L115

**Pull request merged**
