### PR TITLE
Unicode Length

### LINKED ISSUE #1183: Add the option for unicode length of a message in max message length module.
```py
a = u"🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈹🈴🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈹🈴🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯🈷🈶🈵🈚🈸🈲🈳 NaM 🈹🈴🈺🈯"
b = "PogChamp 123"

print(len(a.encode("utf-16")) / 2 - 1, len(a))  # 499.0 292
print(len(b.encode("utf-16")) / 2 - 1, len(b))  # 12.0 12
```

### PR DESCRIPTION
**Pull request by TroyDota**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable
- [ ] Documentation in docs/ or install-docs/ was updated, if applicable

fixes #1183

### CODE REVIEW

**Comment by RAnders00** [comment]
I don't think I'm in favour of merging this PR at all. pajbot2's message height calculation module is the correct solution to the original issue. This just feels like a hack that solves this one particular way to bypass the length limit, not to mention that message length limit is a bad moderation policy anyways (since message height exists now)

**Comment by alazymeme** [comment]
That unicode spam is most often covered under ascii protection:
image

**Comment by pajlada** [comment]
I don't believe this will serve the general public well enough to warrant being included in the main project, it has the chance of confusing/misleading people more than helping.

**Comment by TroyDota** [comment]
Sadge

**Pull request closed without merging**
