### PR TITLE
Create a clip command module

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

I created a clip command module that simply allows the viewer to type `!clip` and it will clip the last 30 seconds of the stream.

### CODE REVIEW

**Comment by alazymeme** [comment]
The problem I'm having at the moment, is that the clip is created, but twitch inherently is returning nothing when fetching the clip url:
image

Could anyone give some insight as to why this would be happening and how I would go about fixing it?

**Comment by alazymeme** [comment]
PR is dependent on https://github.com/pajbot/pajbot/pull/886

**Comment by RAnders00** [comment]
Mind if I mark this as a draft in the meantime?

**Comment by alazymeme** [comment]
> Mind if I mark this as a draft in the meantime?

No

**Comment by alazymeme** [comment]
Decided not to implement discord webhook functionality yet, will work on it at a later date.

**Pull request merged**
