### PR TITLE
Update status badge in readme file

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
is this some kind of joke that the CI doesnt run on this pull request?

**Comment by alazymeme** [comment]
> is this some kind of joke that the CI doesnt run on this pull request?

Could be because ci ignores md files: https://github.com/pajbot/pajbot/blob/master/.github/workflows/build.yml#L6-L12

**Comment by RAnders00** [comment]
Well it should run because the check-format also checks the format of .md files.

**Comment by alazymeme** [comment]
image ...

**Pull request merged**
