### PR TITLE
Semantic ui dark mode

### PR DESCRIPTION
**Pull request by alazymeme**
Replaced the blinding default light mode with a custom dark mode. Working example: https://bot.alazymeme.com/

Fixes https://github.com/pajbot/pajbot/issues/653

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [ ] Documentation in docs/ or install-docs/ was updated, if applicable

### CODE REVIEW

**Comment by alazymeme** [comment]
image
Need to properly fix this as opposed to a scuffed CSS border fix.

**Comment by RAnders00** [comment]
image

If I visit it, it looks like this. Can you fix the grey bar at the bottom, and the search input box being light?

**Comment by RAnders00** [comment]
Also, before you waste too much time on this, have you seen this yet? https://semantic-ui-forest.com/themes/

**Comment by RAnders00** [comment]
And on a last note, dark mode should be a setting and/or automatic toggle based on a `@media` query.

**Comment by alazymeme** [comment]
> 
> 
> image
> 
> If I visit it, it looks like this. Can you fix the grey bar at the bottom, and the search input box being light?

Are you talking about the white bar? I can't see that on my end https://i.nuuls.com/_y8DF.png

> 
> 
> Also, before you waste too much time on this, have you seen this yet? https://semantic-ui-forest.com/themes/

Yes I've used the darkly theme (which is shit) and the cyborg theme (which is also shit). I decided to keep with the semantic ui theme and just make adjustments according to that.

> 
> 
> And on a last note, dark mode should be a setting and/or automatic toggle based on a `@media` query.

There have been quite a few changes - so I'm not 100% sure how to integrate a `@media` query. I also didn't have plans to make a switcher.

**Comment by pajlada** [comment]
I would only merge this PR if it: Keeps the same (or very similar) style as the default, with a theme picker built in (or some media query thing idk what that is but randers mentioned it)

**Comment by pajlada** [comment]
image

**Pull request closed without merging**
