### PR TITLE
Add system to always run all moderation modules and to combine their results

### PR DESCRIPTION
**Pull request by RAnders00**
I implemented my idea from #1209.

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
I want there to be unit tests for the `ModerationActions.add` logic, either I'll do it if time and motivation allows until next weekend, if I haven't done them until now you have some stream content ideas 1x

And of course i tested it exactly once, with a combination of banphrase and massping, so more testing in general is also needed.

image

**Review by pajlada — APPROVED** [review]
Looks good to me! I haven't tested it out yet, but will do tomorrow together with some unit tests maybe.

Good use of types! and dataclasses look nice

**Comment by pajlada** [comment]
This branch is currently running in #pajlada and #forsen

**Comment by alazymeme** [comment]
@pajlada how's the testing going on this? KKonaSmile

**Comment by pajlada** [comment]
Has worked well in my experience - I will merge this in without tests and we can have tests added at a later point :sunglasses:

**Pull request merged**
