### PR TITLE
Fix bot not correctly tracking online/offline state of stream due to TwitchGame not being deserialized properly

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [ ] I have tested all changes

### CODE REVIEW

**Review by ALazyMeme — APPROVED** [review]

**Review by RAnders00 — APPROVED** [review]

**Comment by pajlada** [comment]
Note, I have not tested this (yet) as I don't have a bot that's running a non-stable version atm given the Helix migration is a breaking change. If someone tests this and confirms it works as expected, feel free to note it here and we can go ahead and merge this in.

**Comment by RAnders00** [comment]
My idea for this situation:
- A new branch `v1.62-hotfixes` that branches off `stable`/`v1.62`
- Rebase this branch onto `v1.62-hotfixes` and merge it into `v1.62-hotfixes`
- Then test the changes on that branch
- Release `v1.62.1` off that branch
- Afterwards, merge `v1.62-hotfixes` into `master`
Downside: `v1.62-hotfixes` would have to stay around forever, unless somebody has a smart idea of avoiding the extra branch that would linger around forever

**Comment by pajlada** [comment]
I ended up making a `pre-helix-migration` branch which v1.62 + changes up to the helix migration scopes were added to the log-in to test this and I can confirm it works. I think making a v1.62.1 release with v1.62 + helix migration scopes + this fix is worthwhile so I'll go ahead and do that

**Comment by pajlada** [comment]
oh and yeah I don't think there's a proper way around leaving the branch, it'll just have to stick around which is fine

**Comment by pajlada** [comment]
@RAnders00 Thoughts on updating the `stable` branch to v1.62.1? It *will* require a force push come v1.63 if we do that, which I don't personally have an issue with

**Comment by pajlada** [comment]
:angry: I didn't follow the release instructions properly, I'm going to re-make the release

**Comment by pajlada** [comment]
ok v1.62.1 is decently properly made now at least, I will use that for stable bots and start migrating some of my bots over to the main branch to give all helix features proper testing

**Comment by RAnders00** [comment]
@pajlada if you merge your new branch into `stable` then I don‘t see how it will require a force push when stable comes around? We will just have to make a merge commit then, and won‘t be able to fast-forward/just update the branch pointer

**Pull request merged**
