### PR TITLE
Added bot_domain variable

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

Fairly self explanatory, added a new variables that references the domain option in the config file

### CODE REVIEW

**Comment by alazymeme** [comment]
@RAnders00 I can work on the first thing you requested, but I did change update the variables file; no? https://github.com/pajbot/pajbot/blob/6112c6fe5b58a7d22a6980e848ebd05e88d9236f/docs/variables.txt

**Comment by RAnders00** [comment]
Sorry @alazymeme not sure why I overlooked that, you're correct, and the changes you made look all good!

**Comment by RAnders00** [comment]
Also, just wanted to point this out: I just picked `bot.web_domain` as an example. It could also be `bot.domain` or `bot.bot_domain`. I have no preference about variable names in that case, you can pick whatever you prefer 😄

**Comment by RAnders00** [comment]
@alazymeme Thank you very much! 🎉

**Pull request merged**
