### PR TITLE
Add safe say function

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

Similar to the `safe_privmsg` and `safe_me` functions, the `safe_say` function will check the response against the banphrases before posting the response. If it is a banned phrase, it won't post anything at all.

### CODE REVIEW

**Review by RAnders00 — CHANGES_REQUESTED** [review]
I would appreciate if you could also directly use the new function, i.e. make the changes to the math and lastfm modules like you wanted to originally. (https://github.com/pajbot/pajbot/issues/1118)

And then the changelog should not say that `safe_say` was added, we don't need changelog entries for things that don't change for external users.

**Comment by alazymeme** [comment]
> I would appreciate if you could also directly use the new function

I can if you'd like; but the changes were more personal with the potential to use them for something else in the future....

Up to you if you still want it added.

**Review by RAnders00 — APPROVED** [review]
I see, I thought you were going to add those changes after this is merged with a different PR. I'll merge this one then.

**Comment by alazymeme** [comment]
> I see, I thought you were going to add those changes after this is merged with a different PR. I'll merge this one then.

It might be something to add banphrase checking to all the modules anyway...since the bot really shouldn't be saying anything that's banphrased. Is that something I should do? I can make a separate pr for it when I get the chance.

**Comment by RAnders00** [comment]
Would love for @pajlada to answer this. I don't really know if there's a problem with that?

**Comment by alazymeme** [comment]
image

Will work on a pr

**Pull request merged**
