### PR TITLE
Prototype new install docs

### PR DESCRIPTION
**Pull request by RAnders00**
I've tried to remove the stuff that is not directly relevant to pajbot.

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

### CODE REVIEW

**Comment by RAnders00** [comment]
The result can be viewed here: https://github.com/pajbot/pajbot/tree/randers00-new-install-docs/install-docs

**Comment by pajlada** [comment]
Looks nice, @alazymeme can use this to set up a bot and let me know if he has any feedback

**Comment by alazymeme** [comment]
First step doesn't work on Ubuntu v19.10 - not sure if you're adding a specific version to the guide though: https://pastebin.com/raw/mcJ1gkCJ

**Comment by alazymeme** [comment]
I'm not sure if I should be using the review function, as conflicting opinions arise, but I'll just leave my feedback here.

**Comment by RAnders00** [comment]
We have found that it would be benefitial to include the CloudFlare domain stuff anyways - at least the certbot how-to from the old steps: https://github.com/pajbot/pajbot/blob/d15b88a9dde00a498157ffa046e05d14259ca53f/install-docs/debian10/install-debian10.txt#L99-L120

**Comment by alazymeme** [comment]
@RAnders00 Will that include the nginx instructions, or is that apart of the new docs?

**Comment by RAnders00** [comment]
the new docs should be clearer about the fact you're supposed to put the streamer's name into every place it says `streamer_name`, especially in the example config file.

I should also put the "full" nginx setup stuff back, sort of as an optional "If you need a full nginx setup to get you started" thing.

**Comment by alazymeme** [comment]
Few things:
- add `sudo apt update` and `sudo apt upgrade` to the start of the script - Just running these two commands fixed some issues for me (a regular pleb wouldn't have thought of this)

- I was running into some permissions issues, but I need to retest this

- The example config file is very "confusing", all the information just seems cluttered with all the comments there. I understand that the comments are beneficial for idiots like me, but they genuinely just confuse me more 4Head

Other than that and adding the certificate instructions from your other guide (for SSL), I also ran into an issue with my own incompetence of not reading the guide. Otherwise it's pretty easy to follow BroBalt

**Comment by alazymeme** [comment]
Might be slightly more useful to include all of these lines in the new guide:

https://github.com/pajbot/pajbot/blob/d15b88a9dde00a498157ffa046e05d14259ca53f/install-docs/debian10/install-debian10.txt#L76-L120

**Comment by alazymeme** [comment]
Also one more thing; add an https redirect config somewhere in the tutorial

**Comment by alazymeme** [comment]
Will run through this again when I get home

**Comment by alazymeme** [comment]
Will test again once the docs get updated with the fixes pajaDank - ping me when they get updated, I've got a channel I need to add it to

**Comment by alazymeme** [comment]
Don't forget to add the http to https redirect

**Pull request merged**
