### PR TITLE
Remove channel specific code

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable

I can understand if this was in pajlada's local versions of pajbot, but I don't see why this should be in master.

### CODE REVIEW

**Comment by pajlada** [comment]
Make an issue and we can figure out the ways to solve for this - for now this will stay

**Comment by ALazyMeme** [comment]
This was an issue: https://github.com/pajbot/pajbot/issues/562
But there's no point re-opening the issue if it'll just go stale again.

**Comment by ALazyMeme** [comment]
Otherwise, don't you have the option of using `UserDispatch.py` for this sort of thing?

**Comment by pajlada** [comment]
Did you link the wrong issue?

**Comment by ALazyMeme** [comment]
> Did you link the wrong issue? 

No? Most of the code that should be removed is in relation to that issue.

**Comment by pajlada** [comment]
I'll investigate more later then, didn't read through it fully - sorry 🙏

**Comment by pajlada** [comment]
This does not solve for #562 rather it removes some local code that shouldn't break anyone else's flow. I agree it's ugly, but I don't see a reason to remove it without providing an alternative solution to the *two* features you're removing.

**Pull request closed without merging**
