### PR TITLE
Update `animate` stylesheet to 4.1.1

### PR DESCRIPTION
**Pull request by ALazyMeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] Documentation in docs/ or install-docs/ was updated, if applicable
- [x] I have tested all changes

Migration guide is here: https://animate.style/#migration

### CODE REVIEW

**Comment by ALazyMeme** [comment]
Notes:
- pulsebig doesn't seem to exist anymore? I couldn't find any entries as to what is the best alternative.
- Nothing seemingly happens when emote combos finish? I couldn't see anything wrong with the code. Usually it's meant to bounce out.

**Comment by ALazyMeme** [comment]
Seemingly I didn't realize that `pulsebig` was a custom class. The changes made seem to fix that issue, but the second issue remains.

**Comment by ALazyMeme** [comment]
The second issue is seemingly non-existent. It all seems to work now. Possible that it was fixed by my previous commit.

**Review by pajlada — APPROVED** [review]
Works as expected both in browser and in OBS :+1:

**Pull request merged**
