### PR TITLE
Cleanup and add more log options to user pages

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [ ] Documentation in docs/ or install-docs/ was updated, if applicable

### CODE REVIEW

**Comment by alazymeme** [comment]
@pajlada DB/login lookups are a little beyond my knowledge at the moment. I can revert the `Twitch Logs` option and work on it at a later date - as I currently don't have time. This was meant to just be a small pr in order to fix the horrible spacing on the current user page:

image

**Comment by pajlada** [comment]
It's fine if you don't do the twitch logs part, but if you want some other logs to show up, the preferred method is still the one I posted in the previous comment

**Comment by alazymeme** [comment]
@pajlada I'm still a slight bit confused on how you wish for this to be implemented. How do you want the variables `logs_link_template` and `logs_link_name` to be implemented? Something similar to the contributors section?

**Comment by alazymeme** [comment]
Well now that overrustle is being shutdown, I'm going to close this and try and figure something else out. Might result in just removing the logs option or something similar

**Pull request closed without merging**
